// Generated by https://quicktype.io

export interface CharacterResponse {
  character: Character;
}

export interface CharactersResponse {
  count: number;
  message: string;
  characters: Character[];
  next: QueryParams | null;
  previous: QueryParams | null;
}

export interface Character {
  name: string;
  mass: string;
  height: string;
  gender: Gender;
  birth_year: string;
  hair_color: string;
  skin_color: string;
  id: string;
  species?: string[];
}

export enum Gender {
  Female = "female",
  Male = "male",
  NA = "n/a",
}

export interface QueryParams {
  page?: string;
}

export interface SpecieResponse {
  specie: Specie;
}

export interface Specie {
  name: string;
  language: string;
  eye_colors: string;
  skin_colors: string;
  designation: string;
  hair_colors: string;
  average_height: string;
  classification: string;
  average_lifespan: string;
}
